Move to python3
yugabyte/yugabyte-installation pull request #27
Opened 2020-02-14 02:17 UTC by iSignal

Use the python3 interpreter.

Remove iteritems which is not in python3

2020-02-14 02:19 UTC, mbautin commented
I would probably keep yb-ctl compatible with Python 2 and Python 3 for now.

2020-02-14 02:20 UTC, mbautin requested changes

2020-02-14 02:20 UTC, mbautin commented on bin/yb-ctl
> +#!/usr/bin/env python3
Let's still keep this as `#!/usr/bin/env python` and make sure it works with Python 2 and Python 3.

2020-02-19 19:24 UTC, kmuthukk approved these changes
Thx!

2020-02-19 19:26 UTC, merged

2020-02-19 19:37 UTC, ramkumarvs commented
@iSignal i tested the code, it doesn't start for me.